---
title: "Group project"
author: "Yun Zhu"
date: "28/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(haven)
library(naniar)
library(gtsummary)
library(pROC)
library(dplyr)
library(caret)
library(polycor)
library(tidyr)
library(Hmisc)
library(mice)
library(here)
library(knitr)

frax_risk <- read_sas(here("data","frax_risk.sas7bdat"), NULL)
frax_risk <-as.data.frame(frax_risk)
```


```{r check missing value}
# delete the observations first
# 
# replace "don't know" and "refused" with NA
dn9<-c("ALQ101","DBQ197","DBQ229","DIQ010","DIQ220","MCQ190","MCQ160C","OSQ010A","OSQ010B","OSQ010C","OSQ040AA","OSQ040BA","OSQ040CA","OSQ070","OSQ130","OSQ170","OSQ200","OSQ140U","SMQ020")
dn999<-c("ALQ130","ALQ140Q","DID040","OSQ140Q")
dn9999<-c("OSQ020A","OSQ020B","OSQ020C","WHD020","WHD110","WHD010")
# no column named WHD140 in this data set
dn99999<-c("MCQ160A","MCQ180A","MCQ180C","MCQ160L","MCQ170L","MCQ180L")
frax_risk[,dn9]<-na_if(frax_risk[,dn9],9)
frax_risk[,dn9]<-na_if(frax_risk[,dn9],7)
frax_risk[,dn999]<-na_if(frax_risk[,dn999],999)
frax_risk[,dn999]<-na_if(frax_risk[,dn999],777)
frax_risk[,dn9999]<-na_if(frax_risk[,dn9999],9999)
frax_risk[,dn9999]<-na_if(frax_risk[,dn9999],7777)
frax_risk[,dn99999]<-na_if(frax_risk[,dn99999],99999)
frax_risk[,dn99999]<-na_if(frax_risk[,dn99999],77777)
# check missing values of all variables
gg_miss_var(frax_risk, show_pct = TRUE)
# pick variables with missing value proportion over 50%
frax_risk_50<-frax_risk[, which(colMeans(is.na(frax_risk)) > 0.5)]
gg_miss_var(frax_risk_50, show_pct = TRUE)
```

```{r check variables with missing value less than 50%}
# missing value more than 20%
frax_risk_2050<-frax_risk[, which((colMeans(is.na(frax_risk)) <= 0.5)&(colMeans(is.na(frax_risk)) > 0.2))]
gg_miss_var(frax_risk_2050, show_pct = TRUE)
length(frax_risk_2050)
# missing value less than 20%
frax_risk_20<-frax_risk[, which(colMeans(is.na(frax_risk)) <= 0.2)]
gg_miss_var(frax_risk_20, show_pct = TRUE)
```

```{r dataframe}
# create a data frame 
df<-frax_risk[, which(colMeans(is.na(frax_risk)) <= 0.4)]
# remove duplicate rows
df<-distinct(df)
# check features with low variance
nearZeroVar(df,saveMetrics = TRUE)
# check features with high correlation
Corr <- NULL
# Chi-square test between two categorical variables. 
# Pearson’s Test between two continuous variables
# Point-Biserial Correlation One categorical and one quantitative variable.
discrete <- c("RIAGENDR","RIDRETH1","SDMVPSU","OSQ010A","OSQ010B","OSQ010C","OSQ130","OSQ170","OSQ200","SMQ020" ,               "ALQ101","ALQ130","ALQ140Q","DIQ010","MCQ160A","MCQ160C","MCQ160L","DBQ197","DBQ229")

complete <- na.omit(df)
for(i in 2:(ncol(complete)-1)){
  for(j in (i+1):ncol(complete)){
    if((names(complete)[i] %in% discrete + names(complete)[j] %in% discrete) != 1){
      Corr <- rbind(Corr, c(names(complete)[i],names(complete)[j], cor.test(complete[,i], complete[,j], method = "pearson")$estimate))
    }else
      Corr <- rbind(Corr, c(names(complete)[i],names(complete)[j], polyserial(complete[,i],complete[,j])))
  }
}
#Corr(BMXBMI, WHD020) = 0.83974550051039
df <-  subset(df, select = -c(SEQN,WHD010,WHD020,WHD110)) # remove high correlated
df <- df[-which(is.na(df$OSQ010A)|is.na(df$OSQ010B)|is.na(df$OSQ010C)),]

# multiple imputation
(fmla <- as.formula(paste(" ~ ", paste(colnames(df), collapse=" +"))))
impute_arg <- aregImpute(formula = fmla, data = df, n.impute = 10, nk=0 )
# Get the imputed values
impute <- impute.transcan(impute_arg, data=df, imputation=1, list.out=TRUE, pr=FALSE, check=FALSE)

# convert the list to the database
impute <- as.data.frame(do.call(cbind,impute))
format(colSums(is.na(df[, sapply(df, anyNA)])) / nrow(df)*100, digits = 2) #DXXOSBMD 
index.na <- which(is.na(df$DXXOSBMD))
Comparison <- data.frame(DXXOSBMD = c(df$DXXOSBMD[-index.na],impute$DXXOSBMD[index.na]),
                         Label = c(rep("Observed",(nrow(impute)-length(index.na))),rep("imputed",length(index.na))))

# remove Survey weights and sampling unit information
impute<-impute[,-c(4:6)]
impute<-impute%>% mutate(fracture=as.factor(ifelse((OSQ010A=="1"|OSQ010B=="1"|OSQ010C=="1"), 1, 0))) # add fracture indicator
impute$fracture <- as.numeric(impute$fracture)-1
frax_risk_men<-impute%>%filter(RIAGENDR==1)
frax_risk_women<-impute%>%filter(RIAGENDR==2)
impute$RIAGENDR <- as.factor(impute$RIAGENDR)
impute$RIDRETH1 <- as.factor(impute$RIDRETH1)
```


```{r imputaion plot}
require(qqplotr)
# Histogram with density plot
p1 <- ggplot(Comparison, aes(DXXOSBMD, colour = Label)) + 
 geom_histogram(aes(y=..density..), colour="lightblue", fill="white")+
 geom_density(alpha=.2, fill="#FF6666") 

# Interleaved histograms
p2 <- ggplot(Comparison, aes(DXXOSBMD, colour = Label)) +
  geom_histogram(fill="white", alpha=0.5)+
  theme(legend.position="right")

#quantile–quantile 
p3 <- ggplot(data = Comparison, mapping = aes(sample = DXXOSBMD, color = Label,fill = Label)) +
    stat_qq_band(alpha=0.3) +
    stat_qq_line() +
    stat_qq_point(alpha=0.1) +
    labs(x = "DXXOSBMD Observed", y = "DXXOSBMD Imputed")
#cumulative distribution
p4 <- ggplot(Comparison, aes(DXXOSBMD, colour = Label)) +
  stat_ecdf() +
    labs(x = "DXXOSBMD", y = "Cumulative Probability")
library(cowplot)
ggdraw() +
  draw_plot(p1, x = 0, y = .5, width = .5, height = .5) +
  draw_plot(p2, x = .5, y = .5, width = .5, height = .5) +
  draw_plot(p3, x = 0, y = 0, width = .5, height = 0.5) +
  draw_plot(p4, x = 0.5, y = 0, width = .5, height = 0.5)

table <- 
  tbl_summary(
    impute,
    by = RIAGENDR # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table
```


```{r LASSO}
library(glmnet)

# Step 1: prepare features for modeling
fracture_variables<-c("OSQ010A","OSQ010B","OSQ010C","fracture")
individual_variables<-c("RIAGENDR","RIDRETH1","RIDAGEYR")
frax_risk_BMD<-dplyr::select(impute,contains("BMD"))
frax_risk_nonBMD<-impute[,!(names(impute) %in% names(frax_risk_BMD)) 
                         & !(names(impute) %in% fracture_variables)
                         & !(names(impute) %in% individual_variables)]
BMD_variables<-colnames(frax_risk_BMD)
nonBMD_variables<-colnames(frax_risk_nonBMD)

#q1
x1 <-scale(model.matrix(fracture~., impute[,!names(impute) %in% c("OSQ010A","OSQ010B","OSQ010C")])[,-1])
y1 <- impute$fracture
set.seed(123)
cv.l1 <- cv.glmnet(x1,y1,family="binomial",nfolds = 5,alpha=1,penalty.factor =c(rep(0,10),rep(1,10),rep(0,8)))
best_lambda.l1<-cv.l1$lambda.min
set.seed(123)
l.mod1<- glmnet(x1,y1,family="binomial",alpha=1,lambda = best_lambda.l1,penalty.factor =c(rep(0,10),rep(1,10),rep(0,8)))
coef.l.min1 <- coef(l.mod1)
feature1 <- rownames(coef.l.min1)[coef.l.min1[,1]!=0][-1]
BMDfeature1<-grep("BMD",feature1,value=T)
BMDfeature1

#q2
x.hip <-scale(model.matrix(OSQ010A~., impute[,!names(impute) %in% c("fracture","OSQ010B","OSQ010C")])[,-1])
y.hip <- impute$OSQ010A
set.seed(123)
cv.l.hip <- cv.glmnet(x.hip,y.hip,family="binomial",nfolds = 5,alpha=1,penalty.factor =c(rep(0,10),rep(1,10),rep(0,8)))
best_lambda.l.hip<-cv.l.hip$lambda.min
set.seed(123)
l.mod.hip<- glmnet(x.hip,y.hip,family="binomial",alpha=1,lambda = best_lambda.l.hip,penalty.factor =c(rep(0,10),rep(1,10),rep(0,8)))
coef.l.min.hip<- coef(l.mod.hip)
feature.hip <- rownames(coef.l.min.hip)[coef.l.min.hip[,1]!=0][-1]
BMDfeature.hip<-grep("BMD",feature.hip,value=T)
BMDfeature.hip
#q3
## men
x.men <-scale(model.matrix(fracture~., frax_risk_men[,!names(frax_risk_men) %in% c("RIAGENDR","OSQ010A","OSQ010B","OSQ010C")])[,-1])
y.men <- frax_risk_men$fracture
set.seed(123)
cv.l.men <- cv.glmnet(x.men,y.men,family="binomial",nfolds = 5,alpha=1,penalty.factor =c(rep(0,6),rep(1,10),rep(0,8)))
best_lambda.l.men<-cv.l.men$lambda.min
set.seed(123)
l.mod.men<- glmnet(x.men,y.men,family="binomial",alpha=1,lambda = best_lambda.l.men,penalty.factor =c(rep(0,6),rep(1,10),rep(0,8)))
coef.l.min.men <- coef(l.mod.men)
feature.men <- rownames(coef.l.min.men)[coef.l.min.men[,1]!=0][-1]
BMDfeature.men<-grep("BMD",feature.men,value=T)
BMDfeature.men

## women
x.women <-scale(model.matrix(fracture~., frax_risk_women[,!names(frax_risk_women) %in% c("RIAGENDR","OSQ010A","OSQ010B","OSQ010C")])[,-1])
y.women <- frax_risk_women$fracture
set.seed(123)
cv.l.women <- cv.glmnet(x.women,y.women,family="binomial",nfolds = 5,alpha=1,penalty.factor =c(rep(0,6),rep(1,10),rep(0,8)))
best_lambda.l.women<-cv.l.women$lambda.min
set.seed(123)
l.mod.women<- glmnet(x.women,y.women,family="binomial",alpha=1,lambda = best_lambda.l.women,penalty.factor =c(rep(0,6),rep(1,10),rep(0,8)))
coef.l.min.women <- coef(l.mod.women)
feature.women <- rownames(coef.l.min.women)[coef.l.min.women[,1]!=0][-1]
BMDfeature.women<-grep("BMD",feature.women,value=T)
BMDfeature.women

```

```{r SVM}
# SVM
library(e1071)
library(caret)
library(pROC)
################################# Q1 #################################
# identify predictors (BMD) of osteoporotic fracture in whole cohort
# ** whole cohort ----
# * data manipulation ----
impute <- impute.transcan(impute_arg, data=df, imputation=1, list.out=TRUE, pr=FALSE, check=FALSE)
impute <- as.data.frame(do.call(cbind,impute))
impute <- impute[,-c(4:6)]
impute <- impute%>% mutate(fracture=as.factor(ifelse((OSQ010A=="1"|OSQ010B=="1"|OSQ010C=="1"), 1, 0)))
data.svm <- impute
# define function to find columns with less than 5 levels and factor them
checkLevels <- function(col,level=5){
  ifelse(length(unique(col)) <= level,1,0)
}
factor.lst <- apply(data.svm,2,checkLevels)
data.svm[,which(factor.lst==1)] <- lapply(data.svm[,which(factor.lst==1)],factor)

# define dataset for question 1, which consider all types of fracture
smp_size <- floor(nrow(impute) * 2/3)
set.seed(5250)
train_ind <- sample(seq_len(nrow(impute)), size = smp_size)
data1 <- data.svm[,!names(data.svm) %in% c("OSQ010A","OSQ010B","OSQ010C")]
data1.train <- data1[train_ind,] # set train dataset for question 1
data1.test <- data1[-train_ind,]

# * find the best kernel using 5 fold cv ----
set.seed(5250)
type <- c("linear","radial","polynomial")
cv.full <- c()
for (i in 1:3){
  mod <- tune.svm(fracture~.,kernel=type[i], #cost=c(0.1,0.5,1,5,10,50),
                  type="C-classification", tunecontrol=tune.control(cross=5),
                  data=data1, probability=FALSE)
  cv.full[i] <- mod$best.performance
}

# * assess the test error using tuned kernel type on predefined test set ----
svmfit = svm(fracture~.,kernel=type[which.min(cv.full)], 
             data=data1.train,cost=1,probability = TRUE)
probs.full <- attr(predict(svmfit, data1.test,probability=TRUE),"probabilities")[,1]
thresh <- mean(data1.test$fracture==0)
preds.full <- ifelse(probs.full>quantile(probs.full,probs=thresh),1,0)
auc(data1.test$fracture, as.numeric(preds.full)) #0.4966
mean(as.numeric(preds.full)==data1.test$fracture) # test accuracy 78.42%

# * assess the feature importance ----
# method1 - failed
# library(rminer)
# fit1 <- fit(fracture~., data=data1, model="svm", C=1)
# svm.imp <- Importance(fit1, data=data1)
# method2
# A simple backwards selection, recursive feature elimination (RFE) algorithm
set.seed(5250)
svmprf.type <- c("svmLinear", "svmRadial","svmPolynomial")
svmProfile <- rfe(select(data1,-fracture), data1$fracture,
                  sizes = c(2, 5, 10, 20),
                  rfeControl = rfeControl(functions = rfFuncs,
                                          number = 20),
                  method = svmprf.type[which.min(cv.full)])
svmProfile$optVariables

## ** identify predictors (BMD) of osteoporotic fracture in men ----
data1.men <- split(data1,data1$RIAGENDR,drop = TRUE)$`1`[,-1]
set.seed(5250)
cv.men <- c()
for (i in 1:3){
  mod <- tune.svm(fracture~.,kernel=type[i], #cost=c(0.1,0.5,1,5,10,50),
                  type="C-classification", tunecontrol=tune.control(cross=5),
                  data=data1.men, probability=FALSE)
  cv.men[i] <- mod$best.performance
}
svmProfile.men <- rfe(data1.men[,-25],data1.men$fracture,
                      sizes = c(2, 5, 10, 20),
                      rfeControl = rfeControl(functions = rfFuncs,
                                              number = 20),
                      method = svmprf.type[which.min(cv.men)])
svmProfile.men$optVariables

## ** identify predictors (BMD) of osteoporotic fracture in women ----
data1.women <- split(data1,data1$RIAGENDR,drop = TRUE)$`2`[,-1]
set.seed(5250)
cv.women <- c()
for (i in 1:3){
  mod <- tune.svm(fracture~.,kernel=type[i], #cost=c(0.1,0.5,1,5,10,50),
                  type="C-classification", tunecontrol=tune.control(cross=5),
                  data=data1.women, probability=FALSE)
  cv.women[i] <- mod$best.performance
}
svmProfile.women <- rfe(data1.women[,-25],data1.women$fracture,
                        sizes = c(2, 5, 10, 20),
                        rfeControl = rfeControl(functions = rfFuncs,
                                                number = 20),
                        method = svmprf.type[which.min(cv.women)])
svmProfile.women$optVariables

#################################### Q2 #######################################
# which BMD measure is the best predictor of hip fracture
data2 <- data.svm[,!names(data.svm) %in% c("fracture","OSQ010B","OSQ010C")]
set.seed(5250)
cv.hip <- c()
for (i in 1:3){
  mod <- tune.svm(OSQ010A~.,kernel=type[i], #cost=c(0.1,0.5,1,5,10,50),
                  type="C-classification", tunecontrol=tune.control(cross=5),
                  data=data2, probability=FALSE)
  cv.hip[i] <- mod$best.performance
}
svmProfile.hip <- rfe(data2[,-which(names(data2)=="OSQ010A")],data2$OSQ010A,
                      sizes = c(2, 5, 10, 20),
                      rfeControl = rfeControl(functions = rfFuncs,
                                              number = 20),
                      method = svmprf.type[which.min(cv.hip)])
svmProfile.hip$optVariables
```

```{r Bayesian Logistic}
# Step 1: prepare features for modeling

fracture_variables<-c("OSQ010A","OSQ010B","OSQ010C","fracture")
individual_variables<-c("RIAGENDR","RIDRETH1","RIDAGEYR")
frax_risk_BMD<-dplyr::select(impute,contains("BMD"))
frax_risk_nonBMD<-impute[,!(names(impute) %in% names(frax_risk_BMD)) 
                         & !(names(impute) %in% fracture_variables)
                         & !(names(impute) %in% individual_variables)]
BMD_variables<-colnames(frax_risk_BMD)
nonBMD_variables<-colnames(frax_risk_nonBMD)

impute[,nonBMD_variables[-10]] <- apply(impute[,nonBMD_variables[-10]],2,as.factor)
# Step 1: Creating a list of all the variables
library(coda)
library(rjags)
library(R2jags)
jagsdata <- as.list(impute[,c(BMD_variables,nonBMD_variables,individual_variables,"fracture")])
jagsdata_men <- as.list(frax_risk_men[,c(BMD_variables,nonBMD_variables,individual_variables,"fracture")])
jagsdata_women <- as.list(frax_risk_women[,c(BMD_variables,nonBMD_variables,individual_variables,"fracture")])
jagsdata$N <- nrow(impute)
jagsdata_men$N <- nrow(frax_risk_men)
jagsdata_women$N <- nrow(frax_risk_women)
# Step 2: Specifying the growth curve model
blogistic <- cat("
model {
for (i in 1:N) {
    logit(p[i]) <- a + b1*DXXOFBMD[i] + b2*DXXNKBMD[i] + b3*DXXTRBMD[i]  +
    b4*DXXINBMD[i] + b5*DXXWDBMD[i] + b6*DXXOSBMD[i] + b7*DXXL1BMD[i] + b8*DXXL2BMD[i] +
    b9*DXXL3BMD[i] + b10*DXXL4BMD[i] + b11*OSQ130[i] + b12*OSQ170[i] + b13*OSQ200[i] +
    b14*SMQ020[i] + b15*ALQ101[i] + b16*DIQ010[i] + b17*MCQ160A[i] + b18*MCQ160C[i] +
    b19*MCQ160L[i] + b20*BMXBMI[i] + b21*DBQ197[i] + b22*DBQ229[i] + b23*RIAGENDR[i] +
    b24*RIDRETH1[i] +b25*RIDAGEYR[i]
    fracture[i] ~ dbern(p[i])
}


# Specifying prior distributions
a ~ dnorm(0,0.01)
b1 ~ dnorm(0,0.01)
b2 ~ dnorm(0,0.01)
b3 ~ dnorm(0,0.01)
b4 ~ dnorm(0,0.01)
b5 ~ dnorm(0,0.01)
b6 ~ dnorm(0,0.01)
b7 ~ dnorm(0,0.01)
b8 ~ dnorm(0,0.01)
b9 ~ dnorm(0,0.01)
b10 ~ dnorm(0,0.01)
b11 ~ dnorm(0,0.01)
b12 ~ dnorm(0,0.01)
b13 ~ dnorm(0,0.01)
b14 ~ dnorm(0,0.01)
b15 ~ dnorm(0,0.01)
b16 ~ dnorm(0,0.01)
b17 ~ dnorm(0,0.01)
b18 ~ dnorm(0,0.01)
b19 ~ dnorm(0,0.01)
b20 ~ dnorm(0,0.01)
b21 ~ dnorm(0,0.01)
b22 ~ dnorm(0,0.01)
b23 ~ dnorm(0,0.01)
b24 ~ dnorm(0,0.01)
b25 ~ dnorm(0,0.01)

}

",file = "blogistic.txt")

# Step3: Run the MCMC 
# parameters
params  <- c("a","b1","b2","b3","b4","b5","b6","b7","b8","b9","b10",
             "b11","b12","b13","b14","b15","b16","b17","b18","b19","b20","b21",
             "b22","b23","b24","b25")
# run MCMC
set.seed(1)
model<-jags(data=jagsdata, parameters.to.save=params, model.file="blogistic.txt",
    n.chains=3, n.iter=20000, n.burnin=500,
    n.thin=1,quiet = TRUE)
model_men <-jags(data=jagsdata_men, parameters.to.save=params, model.file="blogistic.txt",
    n.chains=3, n.iter=20000, n.burnin=500,
    n.thin=1,quiet = TRUE)
model_women <-jags(data=jagsdata_women, parameters.to.save=params, model.file="blogistic.txt",
    n.chains=3, n.iter=20000, n.burnin=500,
    n.thin=1,quiet = TRUE)
# Step4: Check convergence
if(T){
SArray<- model$BUGSoutput$sims.array
for(i in 1:length(params)){ 
    nn<-params[i]
    # Autocorrelation plot
    acf( SArray[,1,nn], lag.max = 50,
         main=paste("Autocorrelation plot of",nn,"(chain1)"))
    acf( SArray[,2,nn], lag.max = 50,
         main=paste("Autocorrelation plot of",nn,"(chain2)")) 
    acf( SArray[,3,nn], lag.max = 50,
         main=paste("Autocorrelation plot of",nn,"(chain3)"))
    # trace plot
    matplot(501:20000,SArray[,,nn], 
            main=paste("Trace plot of",nn),
            xlab="interactions",ylab=nn,type="l") 
    }
}
# statistics
kable(model$BUGSoutput$summary[params,],dig=3,
      caption = "Statistics of the fitted parameters")
kable(model_men$BUGSoutput$summary[params,],dig=3,
      caption = "Statistics of the fitted parameters for men")
kable(model_women$BUGSoutput$summary[params,],dig=3,
      caption = "Statistics of the fitted parameters for women")
```


```{r visualization}
# use imputed values to do data visualization
fracture <-impute$fracture
gender <- impute$RIAGENDR
bmdtest <- select(impute,contains("BMD"))
bmdtest$fracture <- fracture
bmdtest$gender <- factor(gender,levels=c("1","2"),labels=c("male","female"))

colMeans(select(bmdtest,-c(fracture,gender)),na.rm = TRUE)
bmdtest2 <- pivot_longer(bmdtest, cols=starts_with("DXX"),names_to = "DXA_scans", 
                         values_to = "value",values_drop_na = TRUE)

# density plot of DXA values for males/females
ggplot(bmdtest2, aes(x=value,fill=gender))+
  facet_wrap(vars(DXA_scans),ncol=4)+
  geom_density(alpha=0.4)+
  theme_minimal()+
  scale_fill_manual(values=c("lightblue","lightpink"))+
  labs(title = "Density Plot for BMD Values")

# density plot of DXA values for fracture/no fracture (contain NA)
ggplot(bmdtest2, aes(x=value,fill=fracture))+
  facet_wrap(vars(DXA_scans),ncol=4)+
  geom_density(alpha=0.3)+
  theme_minimal()+
  labs(title = "Density Plot for BMD Values")

# mosaic plot of gender VS fracture
t <- table(bmdtest2$fracture, bmdtest2$gender)
mosaicplot(t, color = c("lightblue", "lightpink"),xlab = "Oseoporosis Fracture", 
           ylab = "Gender",main = NA)
```



```{r, eval=TRUE}
# LOGISTIC REGRESSION
library(car)
library(pROC)
lr_model <- glm(fracture~., family=binomial(link='logit'), 
                data=impute[,!names(impute) %in% c("OSQ010A","OSQ010B","OSQ010C")])
summary(lr_model)$coef
vif(lr_model)
# all DXX variable are highly correlated! 
# but other variable ok bc vif < 5

#Split into Train and Test
set.seed(19999)
lr_data <- impute[,!names(impute) %in% c("OSQ010A","OSQ010B","OSQ010C")]
lr_training_index <- sample(nrow(lr_data), round(nrow(lr_data)*1/2))
lr_train <- lr_data[lr_training_index,]
lr_test <- lr_data[-lr_training_index,]

#Fit the Model
#Total Femur BMD (DXXOFBMD)
lr_model_of <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOFBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_of)$coef
vif(lr_model_of)

#Femoral Neck BMD (DXXNKBMD)
lr_model_nk <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXNKBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_nk)$coef
vif(lr_model_nk)

#Trochanter BMD (DXXTRBMD)
lr_model_tr <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXTRBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_tr)$coef
vif(lr_model_tr)

#Intertrochanter BMD (DXXINBMD)
lr_model_in <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXINBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_in)$coef
vif(lr_model_in)

#Ward's triangle BMD (DXXWDBMD)
lr_model_wd <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXWDBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_wd)$coef
vif(lr_model_wd)

#Total Spine BMD (DXXOSBMD)
lr_model_os <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOSBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_os)$coef
vif(lr_model_os)

#L1 BMD (DXXL1BMD)
lr_model_l1 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL1BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_l1)$coef
vif(lr_model_l1)

#L2 BMD (DXXL2BMD)
lr_model_l2 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL2BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_l2)$coef
vif(lr_model_l2)

#L3 BMD (DXXL3BMD)
lr_model_l3 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL3BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_l3)$coef
vif(lr_model_l3)

#L4 BMD (DXXL4BMD)
lr_model_l4 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL4BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
summary(lr_model_l4)$coef
vif(lr_model_l4)


######## Check Performance ########
#Brier score
#Ward's triangle BMD = lowest brier
#The results are the same even when I repeat in the for loop about 20 times 
lr_model_of_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_of, newdata=lr_test, type="response"))^2)
lr_model_nk_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_nk, newdata=lr_test, type="response"))^2)
lr_model_tr_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_tr, newdata=lr_test, type="response"))^2)
lr_model_in_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_in, newdata=lr_test, type="response"))^2)
lr_model_wd_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_wd, newdata=lr_test, type="response"))^2)
lr_model_os_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_os, newdata=lr_test, type="response"))^2)
lr_model_l1_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_l1, newdata=lr_test, type="response"))^2)
lr_model_l2_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_l2, newdata=lr_test, type="response"))^2)
lr_model_l3_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_l3, newdata=lr_test, type="response"))^2)
lr_model_l4_brier <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_l4, newdata=lr_test, type="response"))^2)

brier <- cbind(lr_model_of_brier,lr_model_nk_brier,lr_model_tr_brier,lr_model_in_brier,lr_model_wd_brier,
      lr_model_os_brier,lr_model_l1_brier,lr_model_l2_brier,lr_model_l3_brier,lr_model_l4_brier)
colnames(brier) <- c("Total Femur", "Femoral Neck", "Trochanter", "Intertrochanter", 
                     "Ward's triangle","Total spine","L1","L2","L3","L4")
brier
min(brier)



#Accuracy
pred_of_q1 <- predict(lr_model_of, newdata = lr_test,type="response")
pred_nk_q1 <- predict(lr_model_nk, newdata = lr_test,type="response")
pred_tr_q1 <- predict(lr_model_tr, newdata = lr_test,type="response")
pred_in_q1 <- predict(lr_model_in, newdata = lr_test,type="response")
pred_wd_q1 <- predict(lr_model_wd, newdata = lr_test,type="response")
pred_os_q1 <- predict(lr_model_os, newdata = lr_test,type="response")
pred_l1_q1 <- predict(lr_model_l1, newdata = lr_test,type="response")
pred_l2_q1 <- predict(lr_model_l2, newdata = lr_test,type="response")
pred_l3_q1 <- predict(lr_model_l3, newdata = lr_test,type="response")
pred_l4_q1 <- predict(lr_model_l4, newdata = lr_test,type="response")

pred_of_acc_q1 <- ifelse(pred_of_q1>0.5, 1, 0)
lr_model_of_table_q1 <- table(pred_of_acc_q1,lr_test$fracture)
lr_model_of_acc_q1 <- sum(diag(lr_model_of_table_q1))/sum(lr_model_of_table_q1)

pred_nk_acc_q1 <- ifelse(pred_nk_q1>0.5, 1, 0)
lr_model_nk_table_q1 <- table(pred_nk_acc_q1,lr_test$fracture)
lr_model_nk_acc_q1 <- sum(diag(lr_model_nk_table_q1))/sum(lr_model_nk_table_q1)

pred_tr_acc_q1 <- ifelse(pred_tr_q1>0.5, 1, 0)
lr_model_tr_table_q1 <- table(pred_tr_acc_q1,lr_test$fracture)
lr_model_tr_acc_q1 <- sum(diag(lr_model_tr_table_q1))/sum(lr_model_tr_table_q1)

pred_in_acc_q1 <- ifelse(pred_in_q1>0.5, 1, 0)
lr_model_in_table_q1 <- table(pred_in_acc_q1,lr_test$fracture)
lr_model_in_acc_q1 <- sum(diag(lr_model_in_table_q1))/sum(lr_model_in_table_q1)

pred_wd_acc_q1 <- ifelse(pred_wd_q1>0.5, 1, 0)
lr_model_wd_table_q1 <- table(pred_wd_acc_q1,lr_test$fracture)
lr_model_wd_acc_q1 <- sum(diag(lr_model_wd_table_q1))/sum(lr_model_wd_table_q1)
  
pred_os_acc_q1 <- ifelse(pred_os_q1>0.5, 1, 0)
lr_model_os_table_q1 <- table(pred_os_acc_q1,lr_test$fracture)
lr_model_os_acc_q1 <- sum(diag(lr_model_os_table_q1))/sum(lr_model_os_table_q1)
  
pred_l1_acc_q1 <- ifelse(pred_l1_q1>0.5, 1, 0)
lr_model_l1_table_q1 <- table(pred_l1_acc_q1,lr_test$fracture)
lr_model_l1_acc_q1 <- sum(diag(lr_model_l1_table_q1))/sum(lr_model_l1_table_q1)
  
pred_l2_acc_q1 <- ifelse(pred_l2_q1>0.5, 1, 0)
lr_model_l2_table_q1 <- table(pred_l2_acc_q1,lr_test$fracture)
lr_model_l2_acc_q1 <- sum(diag(lr_model_l2_table_q1))/sum(lr_model_l2_table_q1)
  
pred_l3_acc_q1 <- ifelse(pred_l3_q1>0.5, 1, 0)
lr_model_l3_table_q1 <- table(pred_l3_acc_q1,lr_test$fracture)
lr_model_l3_acc_q1 <- sum(diag(lr_model_l3_table_q1))/sum(lr_model_l3_table_q1)
  
pred_l4_acc_q1 <- ifelse(pred_l4_q1>0.5, 1, 0)
lr_model_l4_table_q1 <- table(pred_l4_acc_q1,lr_test$fracture)
lr_model_l4_acc_q1 <- sum(diag(lr_model_l4_table_q1))/sum(lr_model_l4_table_q1)

accuracy_q1 <- c(lr_model_of_acc_q1,lr_model_nk_acc_q1,lr_model_tr_acc_q1,lr_model_in_acc_q1,lr_model_wd_acc_q1,lr_model_os_acc_q1,lr_model_l1_acc_q1,lr_model_l2_acc_q1,lr_model_l3_acc_q1,lr_model_l4_acc_q1)
barplot_names <- c("Total Femur","Femoral Neck","Trochanter","Intertrochanter","Ward's Triangle","Total Spine","L1","L2","L3","L4")
par(mar=c(11,11,4,4))
barplot(accuracy_q1,names.arg=barplot_names,ylab="Accuracy",las=2)
```


```{r, eval=TRUE}
#### MORE ROBUST COMPARISON ####
# Using a for loop
lr_model_of_brier <- c()
lr_model_nk_brier <- c()
lr_model_tr_brier <- c()
lr_model_in_brier <- c()
lr_model_wd_brier <- c()
lr_model_os_brier <- c()
lr_model_l1_brier <- c()
lr_model_l2_brier <- c()
lr_model_l3_brier <- c()
lr_model_l4_brier <- c()

lr_model_of_auc <- c()
lr_model_nk_auc <- c()
lr_model_tr_auc <- c()
lr_model_in_auc <- c()
lr_model_wd_auc <- c()
lr_model_os_auc <- c()
lr_model_l1_auc <- c()
lr_model_l2_auc <- c()
lr_model_l3_auc <- c()
lr_model_l4_auc <- c()

lr_model_of_acc <- c()
lr_model_nk_acc <- c()
lr_model_tr_acc <- c()
lr_model_in_acc <- c()
lr_model_wd_acc <- c()
lr_model_os_acc <- c()
lr_model_l1_acc <- c()
lr_model_l2_acc <- c()
lr_model_l3_acc <- c()
lr_model_l4_acc <- c()

for(i in 1:30){
  lr_data <- impute[,!names(impute) %in% c("OSQ010A","OSQ010B","OSQ010C")]
  lr_training_index <- sample(nrow(lr_data), round(nrow(lr_data)*1/2))
  lr_train <- lr_data[lr_training_index,]
  lr_test <- lr_data[-lr_training_index,]
  
  #1. Total Femur BMD (DXXOFBMD)
  lr_model_of <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOFBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
  
  #2. Femoral Neck BMD (DXXNKBMD)
  lr_model_nk <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXNKBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #3. Trochanter BMD (DXXTRBMD)
  lr_model_tr <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXTRBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #4. Intertrochanter BMD (DXXINBMD)
  lr_model_in <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXINBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #5. Ward's triangle BMD (DXXWDBMD)
  lr_model_wd <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXWDBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #6. Total Spine BMD (DXXOSBMD)
  lr_model_os <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOSBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #7. L1 BMD (DXXL1BMD)
  lr_model_l1 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL1BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #8. L2 BMD (DXXL2BMD)
  lr_model_l2 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL2BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #9. L3 BMD (DXXL3BMD)
  lr_model_l3 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL3BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)

  #10. L4 BMD (DXXL4BMD)
  lr_model_l4 <- glm(fracture~RIAGENDR+RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL4BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train)
  
  #Brier
  lr_model_of_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                             predict(lr_model_of, newdata=lr_test, type="response"))^2)
  lr_model_nk_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_nk, newdata=lr_test, type="response"))^2)
  lr_model_tr_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_tr, newdata=lr_test, type="response"))^2)
  lr_model_in_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_in, newdata=lr_test, type="response"))^2)
  lr_model_wd_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_wd, newdata=lr_test, type="response"))^2)
  lr_model_os_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_os, newdata=lr_test, type="response"))^2)
  lr_model_l1_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_l1, newdata=lr_test, type="response"))^2)
  lr_model_l2_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_l2, newdata=lr_test, type="response"))^2)
  lr_model_l3_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_l3, newdata=lr_test, type="response"))^2)
  lr_model_l4_brier[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_l4, newdata=lr_test, type="response"))^2)
  
  #AUC
  pred_of <- predict(lr_model_of, newdata = lr_test,type="response")
  roc_of <- roc(fracture~pred_of, data=lr_test)
  lr_model_of_auc[i] <- roc_of$auc
  #lr_model_of_table <- table(pred_of,lr_test$fracture)[2:1,2:1]
  #lr_model_of_acc[i] <- sum(diag(lr_model_of_table))/sum(lr_model_of_table)
  
  pred_nk <- predict(lr_model_nk, newdata = lr_test,type="response")
  roc_nk <- roc(fracture~pred_nk, data=lr_test)
  lr_model_nk_auc[i] <- roc_nk$auc
  #lr_model_nk_table <- table(pred_nk,lr_test$fracture)[2:1,2:1]
  #lr_model_nk_acc[i] <- sum(diag(lr_model_nk_table))/sum(lr_model_nk_table)
  
  pred_tr <- predict(lr_model_tr, newdata = lr_test,type="response")
  roc_tr <- roc(fracture~pred_tr, data=lr_test)
  lr_model_tr_auc[i] <- roc_tr$auc
  #lr_model_tr_table <- table(pred_tr,lr_test$fracture)[2:1,2:1]
  #lr_model_tr_acc[i] <- sum(diag(lr_model_tr_table))/sum(lr_model_tr_table)
  
  pred_in <- predict(lr_model_in, newdata = lr_test,type="response")
  roc_in <- roc(fracture~pred_in, data=lr_test)
  lr_model_in_auc[i] <- roc_nk$auc
  #lr_model_in_table <- table(pred_in,lr_test$fracture)[2:1,2:1]
  #lr_model_in_acc[i] <- sum(diag(lr_model_in_table))/sum(lr_model_in_table)
  
  pred_wd <- predict(lr_model_wd, newdata = lr_test,type="response")
  roc_wd <- roc(fracture~pred_wd, data=lr_test)
  lr_model_wd_auc[i] <- roc_wd$auc
  #lr_model_wd_table <- table(pred_wd,lr_test$fracture)[2:1,2:1]
  #lr_model_wd_acc[i] <- sum(diag(lr_model_wd_table))/sum(lr_model_wd_table)
  
  pred_os <- predict(lr_model_os, newdata = lr_test,type="response")
  roc_os <- roc(fracture~pred_os, data=lr_test)
  lr_model_os_auc[i] <- roc_os$auc
  #lr_model_os_table <- table(pred_os,lr_test$fracture)[2:1,2:1]
  #lr_model_os_acc[i] <- sum(diag(lr_model_os_table))/sum(lr_model_os_table)
  
  pred_l1 <- predict(lr_model_l1, newdata = lr_test,type="response")
  roc_l1 <- roc(fracture~pred_l1, data=lr_test)
  lr_model_l1_auc[i] <- roc_l1$auc
  #lr_model_l1_table <- table(pred_l1,lr_test$fracture)[2:1,2:1]
  #lr_model_l1_acc[i] <- sum(diag(lr_model_l1_table))/sum(lr_model_l1_table)
  
  pred_l2 <- predict(lr_model_l2, newdata = lr_test,type="response")
  roc_l2 <- roc(fracture~pred_l2, data=lr_test)
  lr_model_l2_auc[i] <- roc_l2$auc
  #lr_model_l2_table <- table(pred_l2,lr_test$fracture)[2:1,2:1]
  #lr_model_l2_acc[i] <- sum(diag(lr_model_l2_table))/sum(lr_model_l2_table)
  
  pred_l3 <- predict(lr_model_l3, newdata = lr_test,type="response")
  roc_l3 <- roc(fracture~pred_l3, data=lr_test)
  lr_model_l3_auc[i] <- roc_l3$auc
  #lr_model_l3_table <- table(pred_l3,lr_test$fracture)[2:1,2:1]
  #lr_model_l3_acc[i] <- sum(diag(lr_model_l3_table))/sum(lr_model_l3_table)
  
  pred_l4 <- predict(lr_model_l4, newdata = lr_test,type="response")
  roc_l4 <- roc(fracture~pred_l4, data=lr_test)
  lr_model_l4_auc[i] <- roc_l4$auc
  #lr_model_l4_table <- table(pred_l4,lr_test$fracture)[2:1,2:1]
  #lr_model_l4_acc[i] <- sum(diag(lr_model_l4_table))/sum(lr_model_l4_table)
  
  #Accuracy
  pred_of_acc <- ifelse(pred_of>0.5, 1, 0)
  lr_model_of_table <- table(pred_of_acc,lr_test$fracture)
  lr_model_of_acc[i] <- sum(diag(lr_model_of_table))/sum(lr_model_of_table)
  
  pred_nk_acc <- ifelse(pred_nk>0.5, 1, 0)
  lr_model_nk_table <- table(pred_nk_acc,lr_test$fracture)
  lr_model_nk_acc[i] <- sum(diag(lr_model_nk_table))/sum(lr_model_nk_table)
  
  pred_tr_acc <- ifelse(pred_tr>0.5, 1, 0)
  lr_model_tr_table <- table(pred_tr_acc,lr_test$fracture)
  lr_model_tr_acc[i] <- sum(diag(lr_model_tr_table))/sum(lr_model_tr_table)
  
  pred_in_acc <- ifelse(pred_in>0.5, 1, 0)
  lr_model_in_table <- table(pred_in_acc,lr_test$fracture)
  lr_model_in_acc[i] <- sum(diag(lr_model_in_table))/sum(lr_model_in_table)
  
  pred_wd_acc <- ifelse(pred_wd>0.5, 1, 0)
  lr_model_wd_table <- table(pred_wd_acc,lr_test$fracture)
  lr_model_wd_acc[i] <- sum(diag(lr_model_wd_table))/sum(lr_model_wd_table)
  
  pred_os_acc <- ifelse(pred_os>0.5, 1, 0)
  lr_model_os_table <- table(pred_os_acc,lr_test$fracture)
  lr_model_os_acc[i] <- sum(diag(lr_model_os_table))/sum(lr_model_os_table)
  
  pred_l1_acc <- ifelse(pred_l1>0.5, 1, 0)
  lr_model_l1_table <- table(pred_l1_acc,lr_test$fracture)
  lr_model_l1_acc[i] <- sum(diag(lr_model_l1_table))/sum(lr_model_l1_table)
  
  pred_l2_acc <- ifelse(pred_l2>0.5, 1, 0)
  lr_model_l2_table <- table(pred_l2_acc,lr_test$fracture)
  lr_model_l2_acc[i] <- sum(diag(lr_model_l2_table))/sum(lr_model_l2_table)
  
  pred_l3_acc <- ifelse(pred_l3>0.5, 1, 0)
  lr_model_l3_table <- table(pred_l3_acc,lr_test$fracture)
  lr_model_l3_acc[i] <- sum(diag(lr_model_l3_table))/sum(lr_model_l3_table)
  
  pred_l4_acc <- ifelse(pred_l4>0.5, 1, 0)
  lr_model_l4_table <- table(pred_l4_acc,lr_test$fracture)
  lr_model_l4_acc[i] <- sum(diag(lr_model_l4_table))/sum(lr_model_l4_table)
}

brier <- cbind(lr_model_of_brier,lr_model_nk_brier,lr_model_tr_brier,lr_model_in_brier,lr_model_wd_brier,
      lr_model_os_brier,lr_model_l1_brier,lr_model_l2_brier,lr_model_l3_brier,lr_model_l4_brier)
brier
table(apply(brier, 1, which.min))
#5. Ward' Triangle has the best brier

auc_value <- cbind(lr_model_of_auc,lr_model_nk_auc,lr_model_tr_auc,lr_model_in_auc,lr_model_wd_auc,lr_model_os_auc,lr_model_l1_auc,lr_model_l2_auc,lr_model_l3_auc,lr_model_l4_auc)
auc_value
table(apply(auc_value, 1, which.max))
#5. Ward's Triangle has the best AUC

acc_value <- cbind(lr_model_of_acc,lr_model_nk_acc,lr_model_tr_acc,lr_model_in_acc,lr_model_wd_acc,lr_model_os_acc,lr_model_l1_acc,lr_model_l2_acc,lr_model_l3_acc,lr_model_l4_acc)
acc_value
table(apply(acc_value, 1, which.max))
#1. Total Femur has the highest acuracy

summary(lr_model_os)



##################  MEN AND WOMEN  ####################
lr_men_data <- frax_risk_men[,!names(frax_risk_men) %in% c("RIAGENDR","OSQ010A","OSQ010B","OSQ010C")]
lr_women_data <- frax_risk_women[,!names(frax_risk_women) %in% c("RIAGENDR","OSQ010A","OSQ010B","OSQ010C")]

# MEN #
lr_model_of_brier_m <- c()
lr_model_nk_brier_m <- c()
lr_model_tr_brier_m <- c()
lr_model_in_brier_m <- c()
lr_model_wd_brier_m <- c()
lr_model_os_brier_m <- c()
lr_model_l1_brier_m <- c()
lr_model_l2_brier_m <- c()
lr_model_l3_brier_m <- c()
lr_model_l4_brier_m <- c()

lr_model_of_auc_m <- c()
lr_model_nk_auc_m <- c()
lr_model_tr_auc_m <- c()
lr_model_in_auc_m <- c()
lr_model_wd_auc_m <- c()
lr_model_os_auc_m <- c()
lr_model_l1_auc_m <- c()
lr_model_l2_auc_m <- c()
lr_model_l3_auc_m <- c()
lr_model_l4_auc_m <- c()

lr_model_of_acc_m <- c()
lr_model_nk_acc_m <- c()
lr_model_tr_acc_m <- c()
lr_model_in_acc_m <- c()
lr_model_wd_acc_m <- c()
lr_model_os_acc_m <- c()
lr_model_l1_acc_m <- c()
lr_model_l2_acc_m <- c()
lr_model_l3_acc_m <- c()
lr_model_l4_acc_m <- c()

set.seed(999989)
for(i in 1:30){
  lr_training_index_m <- sample(nrow(lr_men_data), round(nrow(lr_men_data)*1/2))
  lr_train_m <- lr_men_data[lr_training_index_m,]
  lr_test_m <- lr_men_data[-lr_training_index_m,]
  
  #1. Total Femur BMD (DXXOFBMD)
  lr_model_of_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOFBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)
  
  #2. Femoral Neck BMD (DXXNKBMD)
  lr_model_nk_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXNKBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #3. Trochanter BMD (DXXTRBMD)
  lr_model_tr_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXTRBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #4. Intertrochanter BMD (DXXINBMD)
  lr_model_in_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXINBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #5. Ward's triangle BMD (DXXWDBMD)
  lr_model_wd_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXWDBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #6. Total Spine BMD (DXXOSBMD)
  lr_model_os_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOSBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #7. L1 BMD (DXXL1BMD)
  lr_model_l1_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL1BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #8. L2 BMD (DXXL2BMD)
  lr_model_l2_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL2BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #9. L3 BMD (DXXL3BMD)
  lr_model_l3_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL3BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)

  #10. L4 BMD (DXXL4BMD)
  lr_model_l4_m <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL4BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_m)
  
  #Brier
  lr_model_of_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                             predict(lr_model_of_m, newdata=lr_test_m, type="response"))^2)
  lr_model_nk_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_nk_m, newdata=lr_test_m, type="response"))^2)
  lr_model_tr_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_tr_m, newdata=lr_test_m, type="response"))^2)
  lr_model_in_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_in_m, newdata=lr_test_m, type="response"))^2)
  lr_model_wd_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_wd_m, newdata=lr_test_m, type="response"))^2)
  lr_model_os_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_os_m, newdata=lr_test_m, type="response"))^2)
  lr_model_l1_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_l1_m, newdata=lr_test_m, type="response"))^2)
  lr_model_l2_brier_m[i] <- mean((as.numeric(as.character(lr_test$fracture))-
                               predict(lr_model_l2_m, newdata=lr_test_m, type="response"))^2)
  lr_model_l3_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_l3_m, newdata=lr_test_m, type="response"))^2)
  lr_model_l4_brier_m[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_l4_m, newdata=lr_test_m, type="response"))^2)
  
  #AUC
  pred_of_m <- predict(lr_model_of_m, newdata = lr_test_m,type="response")
  roc_of_m <- roc(fracture~pred_of_m, data=lr_test_m)
  lr_model_of_auc_m[i] <- roc_of_m$auc
  
  pred_nk_m <- predict(lr_model_nk_m, newdata = lr_test_m,type="response")
  roc_nk_m <- roc(fracture~pred_nk_m, data=lr_test_m)
  lr_model_nk_auc_m[i] <- roc_nk_m$auc
  
  pred_tr_m <- predict(lr_model_tr_m, newdata = lr_test_m,type="response")
  roc_tr_m <- roc(fracture~pred_tr_m, data=lr_test_m)
  lr_model_tr_auc_m[i] <- roc_tr_m$auc
  
  pred_in_m <- predict(lr_model_in_m, newdata = lr_test_m,type="response")
  roc_in_m <- roc(fracture~pred_in_m, data=lr_test_m)
  lr_model_in_auc_m[i] <- roc_nk_m$auc
  
  pred_wd_m <- predict(lr_model_wd_m, newdata = lr_test_m,type="response")
  roc_wd_m <- roc(fracture~pred_wd_m, data=lr_test_m)
  lr_model_wd_auc_m[i] <- roc_wd_m$auc
  
  pred_os_m <- predict(lr_model_os_m, newdata = lr_test_m,type="response")
  roc_os_m <- roc(fracture~pred_os_m, data=lr_test_m)
  lr_model_os_auc_m[i] <- roc_os_m$auc
  
  pred_l1_m <- predict(lr_model_l1_m, newdata = lr_test_m,type="response")
  roc_l1_m <- roc(fracture~pred_l1_m, data=lr_test_m)
  lr_model_l1_auc_m[i] <- roc_l1_m$auc
  
  pred_l2_m <- predict(lr_model_l2_m, newdata = lr_test_m,type="response")
  roc_l2_m <- roc(fracture~pred_l2_m, data=lr_test_m)
  lr_model_l2_auc_m[i] <- roc_l2_m$auc
  
  pred_l3_m <- predict(lr_model_l3_m, newdata = lr_test_m,type="response")
  roc_l3_m <- roc(fracture~pred_l3_m, data=lr_test_m)
  lr_model_l3_auc_m[i] <- roc_l3_m$auc
  
  pred_l4_m <- predict(lr_model_l4_m, newdata = lr_test_m,type="response")
  roc_l4_m <- roc(fracture~pred_l4_m, data=lr_test_m)
  lr_model_l4_auc_m[i] <- roc_l4_m$auc
  

  #Accuracy
  pred_of_acc_m <- ifelse(pred_of_m>0.5, 1, 0)
  lr_model_of_table_m <- table(pred_of_acc_m,lr_test_m$fracture)
  lr_model_of_acc_m[i] <- sum(diag(lr_model_of_table_m))/sum(lr_model_of_table_m)
  
  pred_nk_acc_m <- ifelse(pred_nk_m>0.5, 1, 0)
  lr_model_nk_table_m <- table(pred_nk_acc_m,lr_test_m$fracture)
  lr_model_nk_acc_m[i] <- sum(diag(lr_model_nk_table_m))/sum(lr_model_nk_table_m)
  
  pred_tr_acc_m <- ifelse(pred_tr_m>0.5, 1, 0)
  lr_model_tr_table_m <- table(pred_tr_acc_m,lr_test_m$fracture)
  lr_model_tr_acc_m[i] <- sum(diag(lr_model_tr_table_m))/sum(lr_model_tr_table_m)
  
  pred_in_acc_m <- ifelse(pred_in_m>0.5, 1, 0)
  lr_model_in_table_m <- table(pred_in_acc_m,lr_test_m$fracture)
  lr_model_in_acc_m[i] <- sum(diag(lr_model_in_table_m))/sum(lr_model_in_table_m)
  
  pred_wd_acc_m <- ifelse(pred_wd_m>0.5, 1, 0)
  lr_model_wd_table_m <- table(pred_wd_acc_m,lr_test_m$fracture)
  lr_model_wd_acc_m[i] <- sum(diag(lr_model_wd_table_m))/sum(lr_model_wd_table_m)
  
  pred_os_acc_m <- ifelse(pred_os_m>0.5, 1, 0)
  lr_model_os_table_m <- table(pred_os_acc_m,lr_test_m$fracture)
  lr_model_os_acc_m[i] <- sum(diag(lr_model_os_table_m))/sum(lr_model_os_table_m)
  
  pred_l1_acc_m <- ifelse(pred_l1_m>0.5, 1, 0)
  lr_model_l1_table_m <- table(pred_l1_acc_m,lr_test_m$fracture)
  lr_model_l1_acc_m[i] <- sum(diag(lr_model_l1_table_m))/sum(lr_model_l1_table_m)
  
  pred_l2_acc_m <- ifelse(pred_l2_m>0.5, 1, 0)
  lr_model_l2_table_m <- table(pred_l2_acc_m,lr_test_m$fracture)
  lr_model_l2_acc_m[i] <- sum(diag(lr_model_l2_table_m))/sum(lr_model_l2_table_m)
  
  pred_l3_acc_m <- ifelse(pred_l3_m>0.5, 1, 0)
  lr_model_l3_table_m <- table(pred_l3_acc_m,lr_test_m$fracture)
  lr_model_l3_acc_m[i] <- sum(diag(lr_model_l3_table_m))/sum(lr_model_l3_table_m)
  
  pred_l4_acc_m <- ifelse(pred_l4_m>0.5, 1, 0)
  lr_model_l4_table_m <- table(pred_l4_acc_m,lr_test_m$fracture)
  lr_model_l4_acc_m[i] <- sum(diag(lr_model_l4_table_m))/sum(lr_model_l4_table_m)
}

brier_m <- cbind(lr_model_of_brier_m,lr_model_nk_brier_m,lr_model_tr_brier_m,lr_model_in_brier_m,lr_model_wd_brier_m,lr_model_os_brier_m,lr_model_l1_brier_m,lr_model_l2_brier_m,lr_model_l3_brier_m,lr_model_l4_brier_m)
brier_m
table(apply(brier_m, 1, which.min))
#For men, 8. L2 performed the best

auc_value_m <- cbind(lr_model_of_auc_m,lr_model_nk_auc_m,lr_model_tr_auc_m,lr_model_in_auc_m,lr_model_wd_auc_m,lr_model_os_auc_m,lr_model_l1_auc_m,lr_model_l2_auc_m,lr_model_l3_auc_m,lr_model_l4_auc_m)
auc_value_m
table(apply(auc_value_m, 1, which.max))
#For men, 5. Ward's Triangle performed the best

acc_value_m <- cbind(lr_model_of_acc_m,lr_model_nk_acc_m,lr_model_tr_acc_m,lr_model_in_acc_m,lr_model_wd_acc_m,lr_model_os_acc_m,lr_model_l1_acc_m,lr_model_l2_acc_m,lr_model_l3_acc_m,lr_model_l4_acc_m)
acc_value_m
table(apply(acc_value_m, 1, which.max))
#For men, 1. Total Femur BMD had the highest accuracy




# WOMEN #
lr_model_of_brier_w <- c()
lr_model_nk_brier_w <- c()
lr_model_tr_brier_w <- c()
lr_model_in_brier_w <- c()
lr_model_wd_brier_w <- c()
lr_model_os_brier_w <- c()
lr_model_l1_brier_w <- c()
lr_model_l2_brier_w <- c()
lr_model_l3_brier_w <- c()
lr_model_l4_brier_w <- c()

lr_model_of_auc_w <- c()
lr_model_nk_auc_w <- c()
lr_model_tr_auc_w <- c()
lr_model_in_auc_w <- c()
lr_model_wd_auc_w <- c()
lr_model_os_auc_w <- c()
lr_model_l1_auc_w <- c()
lr_model_l2_auc_w <- c()
lr_model_l3_auc_w <- c()
lr_model_l4_auc_w <- c()

lr_model_of_acc_w <- c()
lr_model_nk_acc_w <- c()
lr_model_tr_acc_w <- c()
lr_model_in_acc_w <- c()
lr_model_wd_acc_w <- c()
lr_model_os_acc_w <- c()
lr_model_l1_acc_w <- c()
lr_model_l2_acc_w <- c()
lr_model_l3_acc_w <- c()
lr_model_l4_acc_w <- c()

set.seed(99999999)
for(i in 1:30){
  lr_training_index_w <- sample(nrow(lr_women_data), round(nrow(lr_women_data)*1/2))
  lr_train_w <- lr_women_data[lr_training_index_w,]
  lr_test_w <- lr_women_data[-lr_training_index_w,]
  
  #1. Total Femur BMD (DXXOFBMD)
  lr_model_of_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOFBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)
  
  #2. Femoral Neck BMD (DXXNKBMD)
  lr_model_nk_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXNKBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #3. Trochanter BMD (DXXTRBMD)
  lr_model_tr_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXTRBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #4. Intertrochanter BMD (DXXINBMD)
  lr_model_in_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXINBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #5. Ward's triangle BMD (DXXWDBMD)
  lr_model_wd_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXWDBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #6. Total Spine BMD (DXXOSBMD)
  lr_model_os_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXOSBMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #7. L1 BMD (DXXL1BMD)
  lr_model_l1_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL1BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #8. L2 BMD (DXXL2BMD)
  lr_model_l2_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL2BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #9. L3 BMD (DXXL3BMD)
  lr_model_l3_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL3BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)

  #10. L4 BMD (DXXL4BMD)
  lr_model_l4_w <- glm(fracture~RIDAGEYR+RIDRETH1+OSQ130+OSQ170+OSQ200+SMQ020+DXXL4BMD+ALQ101
                 +DIQ010+MCQ160A+MCQ160L+BMXBMI+DBQ197+DBQ229,
                 family=binomial(link='logit'),
                 data=lr_train_w)
  
  #Brier
  lr_model_of_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                             predict(lr_model_of_w, newdata=lr_test_w, type="response"))^2)
  lr_model_nk_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_nk_w, newdata=lr_test_w, type="response"))^2)
  lr_model_tr_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_tr_w, newdata=lr_test_w, type="response"))^2)
  lr_model_in_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_in_w, newdata=lr_test_w, type="response"))^2)
  lr_model_wd_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_wd_w, newdata=lr_test_w, type="response"))^2)
  lr_model_os_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_os_w, newdata=lr_test_w, type="response"))^2)
  lr_model_l1_brier_w[i] <- mean((as.numeric(as.character(lr_test_m$fracture))-
                               predict(lr_model_l1_w, newdata=lr_test_w, type="response"))^2)
  lr_model_l2_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_l2_w, newdata=lr_test_w, type="response"))^2)
  lr_model_l3_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_l3_w, newdata=lr_test_w, type="response"))^2)
  lr_model_l4_brier_w[i] <- mean((as.numeric(as.character(lr_test_w$fracture))-
                               predict(lr_model_l4_w, newdata=lr_test_w, type="response"))^2)
  
  #AUC
  pred_of_w <- predict(lr_model_of_w, newdata = lr_test_w,type="response")
  roc_of_w <- roc(fracture~pred_of_w, data=lr_test_w)
  lr_model_of_auc_w[i] <- roc_of_w$auc
  
  pred_nk_w <- predict(lr_model_nk_w, newdata = lr_test_w,type="response")
  roc_nk_w <- roc(fracture~pred_nk_w, data=lr_test_w)
  lr_model_nk_auc_w[i] <- roc_nk_w$auc
  
  pred_tr_w <- predict(lr_model_tr_w, newdata = lr_test_w,type="response")
  roc_tr_w <- roc(fracture~pred_tr_w, data=lr_test_w)
  lr_model_tr_auc_w[i] <- roc_tr_w$auc
  
  pred_in_w <- predict(lr_model_in_w, newdata = lr_test_w,type="response")
  roc_in_w <- roc(fracture~pred_in_w, data=lr_test_w)
  lr_model_in_auc_w[i] <- roc_nk_w$auc
  
  pred_wd_w <- predict(lr_model_wd_w, newdata = lr_test_w,type="response")
  roc_wd_w <- roc(fracture~pred_wd_w, data=lr_test_w)
  lr_model_wd_auc_w[i] <- roc_wd_w$auc
  
  pred_os_w <- predict(lr_model_os_w, newdata = lr_test_w,type="response")
  roc_os_w <- roc(fracture~pred_os_w, data=lr_test_w)
  lr_model_os_auc_w[i] <- roc_os_w$auc
  
  pred_l1_w <- predict(lr_model_l1_w, newdata = lr_test_w,type="response")
  roc_l1_w <- roc(fracture~pred_l1_w, data=lr_test_w)
  lr_model_l1_auc_w[i] <- roc_l1_w$auc
  
  pred_l2_w <- predict(lr_model_l2_w, newdata = lr_test_w,type="response")
  roc_l2_w <- roc(fracture~pred_l2_w, data=lr_test_w)
  lr_model_l2_auc_w[i] <- roc_l2_w$auc
  
  pred_l3_w <- predict(lr_model_l3_w, newdata = lr_test_w,type="response")
  roc_l3_w <- roc(fracture~pred_l3_w, data=lr_test_w)
  lr_model_l3_auc_w[i] <- roc_l3_w$auc
  
  pred_l4_w <- predict(lr_model_l4_w, newdata = lr_test_w,type="response")
  roc_l4_w <- roc(fracture~pred_l4_w, data=lr_test_w)
  lr_model_l4_auc_w[i] <- roc_l4_w$auc
  
  #Accuracy
  pred_of_acc_w <- ifelse(pred_of_w>0.5, 1, 0)
  lr_model_of_table_w <- table(pred_of_acc_w,lr_test_w$fracture)
  lr_model_of_acc_w[i] <- sum(diag(lr_model_of_table_w))/sum(lr_model_of_table_w)
  
  pred_nk_acc_w <- ifelse(pred_nk_w>0.5, 1, 0)
  lr_model_nk_table_w <- table(pred_nk_acc_w,lr_test_w$fracture)
  lr_model_nk_acc_w[i] <- sum(diag(lr_model_nk_table_w))/sum(lr_model_nk_table_w)
  
  pred_tr_acc_w <- ifelse(pred_tr_w>0.5, 1, 0)
  lr_model_tr_table_w <- table(pred_tr_acc_w,lr_test_w$fracture)
  lr_model_tr_acc_w[i] <- sum(diag(lr_model_tr_table_w))/sum(lr_model_tr_table_w)
  
  pred_in_acc_w <- ifelse(pred_in_w>0.5, 1, 0)
  lr_model_in_table_w <- table(pred_in_acc_w,lr_test_w$fracture)
  lr_model_in_acc_w[i] <- sum(diag(lr_model_in_table_w))/sum(lr_model_in_table_w)
  
  pred_wd_acc_w <- ifelse(pred_wd_w>0.5, 1, 0)
  lr_model_wd_table_w <- table(pred_wd_acc_w,lr_test_w$fracture)
  lr_model_wd_acc_w[i] <- sum(diag(lr_model_wd_table_w))/sum(lr_model_wd_table_w)
  
  pred_os_acc_w <- ifelse(pred_os_w>0.5, 1, 0)
  lr_model_os_table_w <- table(pred_os_acc_w,lr_test_w$fracture)
  lr_model_os_acc_w[i] <- sum(diag(lr_model_os_table_w))/sum(lr_model_os_table_w)
  
  pred_l1_acc_w <- ifelse(pred_l1_w>0.5, 1, 0)
  lr_model_l1_table_w <- table(pred_l1_acc_w,lr_test_w$fracture)
  lr_model_l1_acc_w[i] <- sum(diag(lr_model_l1_table_w))/sum(lr_model_l1_table_w)
  
  pred_l2_acc_w <- ifelse(pred_l2_w>0.5, 1, 0)
  lr_model_l2_table_w <- table(pred_l2_acc_w,lr_test_w$fracture)
  lr_model_l2_acc_w[i] <- sum(diag(lr_model_l2_table_w))/sum(lr_model_l2_table_w)
  
  pred_l3_acc_w <- ifelse(pred_l3_w>0.5, 1, 0)
  lr_model_l3_table_w <- table(pred_l3_acc_w,lr_test_w$fracture)
  lr_model_l3_acc_w[i] <- sum(diag(lr_model_l3_table_w))/sum(lr_model_l3_table_w)
  
  pred_l4_acc_w <- ifelse(pred_l4_w>0.5, 1, 0)
  lr_model_l4_table_w <- table(pred_l4_acc_w,lr_test_w$fracture)
  lr_model_l4_acc_w[i] <- sum(diag(lr_model_l4_table_w))/sum(lr_model_l4_table_w)
}

brier_w <- cbind(lr_model_of_brier_w,lr_model_nk_brier_w,lr_model_tr_brier_w,lr_model_in_brier_w,lr_model_wd_brier_w,lr_model_os_brier_w,lr_model_l1_brier_w,lr_model_l2_brier_w,lr_model_l3_brier_w,lr_model_l4_brier_w)
brier_w
table(apply(brier_w, 1, which.min))
#For women, 5. Ward's Triangle performed the best

auc_value_w <- cbind(lr_model_of_auc_w,lr_model_nk_auc_w,lr_model_tr_auc_w,lr_model_in_auc_w,lr_model_wd_auc_w,lr_model_os_auc_w,lr_model_l1_auc_w,lr_model_l2_auc_w,lr_model_l3_auc_w,lr_model_l4_auc_w)
auc_value_w
table(apply(auc_value_w, 1, which.max))
#For women, 2. Femoral Neck was the best

acc_value_w <- cbind(lr_model_of_acc_w,lr_model_nk_acc_w,lr_model_tr_acc_w,lr_model_in_acc_w,lr_model_wd_acc_w,lr_model_os_acc_w,lr_model_l1_acc_w,lr_model_l2_acc_w,lr_model_l3_acc_w,lr_model_l4_acc_w)
acc_value_w
table(apply(acc_value_w, 1, which.max))
#For women, 1. Total Femur BMD had the highest accuracy



# Response variable = impute$fracture
# Explanatory Variables =impute[,!names(impute) %in% c("OSQ010A","OSQ010B","OSQ010C")]
#RIDAGEYR = age
#RIDRETH12 = race/ethnicity
#RIDRETH13  
#RIDRETH14 
#RIDRETH15  
#OSQ130 = ever taken prednione or cortione nearly every day for a month or longer 
#OSQ170 = did mother ever fracture a hip     
#OSQ200 = did father ever fracture a hip
#SMQ020 = smoked at least 100 cigarette in life
#DXXOFBMD = total femur BMD     
#DXXNKBMD = femoral neck BMD
#DXXTRBMD = trochanter BMD
#DXXINBMD = intertrochanter BMD
#DXXWDBMD = ward' triangle BMD
#DXXOSBMD = total pine BMD
#DXXL1BMD = L1 BMD
#DXXL2BMD = L2 BMD
#DXXL3BMD = L3 BMD
#DXXL4BMD = L4 BMD
#ALQ101 = had at leat 12 alcoholic drink in the lat year
#DIQ010 = doctor told you have diabete
#MCQ160A = doctor ever aid you have arthriti
#MCQ160C = doctor ever aid you had coronary heart dieaes     
#MCQ160L = ever told you had any liver condition
#BMXBMI = BMI       
#DBQ197 = pat 30 day milk conumption 
#DBQ229 = regular milk ue 5 time per week
```